#pragma once 

#include "Server.h"
#include "Request.h"
#include <queue>
#include <vector>
#include <map>
#include <string>
#include<fstream>
#include<iostream>
#include<set>
#include <utility>
#include <random>
#include<sstream>
#include <thread>
#include <chrono>
#include <algorithm>
#include <cctype>
#include <ctime>


/**
 * @struct LBConfig
 * @brief Stores configuration parameters for the load balancer simulation.
 *
 * LBConfig contains thresholds for scaling decisions, request generation
 * parameters, firewall settings, logging file locations, and clock timing.
 *
 * Values are typically loaded from a configuration text file.
 */
struct LBConfig {
    /** @brief Queue occupancy threshold (per server) under which scaling down is considered. */
    int lowThreshold;
    /** @brief Queue occupancy threshold (per server) above which scaling up is considered. */
    int highThreshold;

    /**
     * @brief Cooldown/rest period (in ticks) required between consecutive scale actions.
     *
     * Prevents the system from scaling too aggressively in short time intervals.
     */    
    int rest;
    /**
     * @brief Cooldown/rest period (in ticks) required between consecutive scale actions.
     *
     * Prevents the system from scaling too aggressively in short time intervals.
     */
    std::vector<std::string> genRange;
    /** @brief Probability (0-100) that a request is generated on a tick. */
    int requestGenProb ;
    /** @brief Minimum request processing time (in ticks). */
    int minRequestTime ;
    /** @brief Maximum request processing time (in ticks). */
    int maxRequestTime ;

    /**
     * @brief Set of IP addresses allowed by the firewall.
     *
     * Requests whose source IP is not in this set are rejected immediately.
     */
    std::set<std::string> range;
    /**
     * @brief Maximum number of requests allowed from one source within a time window.
     *
     * If a source exceeds this threshold inside pingWindow, it is blocked.
     */
    int maxPing ;
    /** @brief Size of the firewall counting window (in ticks). */
    int pingWindow ;
    /** @brief Duration (in ticks) to block a source IP after exceeding maxPing. */
    int blockDuration ;

    /** @brief Output file used for event logs. */
    std::string logFile ;

    /**
     * @brief Clock period used to slow down the simulation.
     *
     * A value of 0 means no delay. Nonzero values represent milliseconds.
     */
    int clockPeriod; 
};

/**
 * @struct LBStats
 * @brief Tracks runtime statistics for a load balancer simulation.
 *
 * These fields count request lifecycle outcomes and scaling decisions
 * over the course of the simulation.
 */
struct LBStats {
    /** @brief Total number of requests generated by the request generator. */
    int generated = 0;
    /** @brief Total number of requests accepted by the firewall after initial queue fill. */
    int accepted = 0;
    /** @brief Total number of requests rejected (firewall rejection and/or block). */
    int rejected = 0;
    /** @brief Total number of requests completed by servers. */
    int completed = 0;
    /** @brief Total number of scale-up events performed. */
    int scaleUps = 0;
    /** @brief Total number of scale-down events performed. */
    int scaleDowns = 0;
};

/**
 * @class LoadBalancer
 * @brief Manages a request queue and a pool of servers for a specific JobType.
 *
 * A LoadBalancer maintains:
 * - A FIFO queue of requests
 * - A vector of servers that process those requests
 * - Configuration values loaded from a config file
 * - Simulation statistics (generated, accepted, rejected, completed, scaling)
 * - Firewall state (rate-limiting and IP blocking)
 *
 * In this simulation, a management load balancer may generate and route requests
 * to other load balancers (e.g., Streaming and Processing) based on request type.
 */
class LoadBalancer{
    public:
        /**
         * @brief Constructs a load balancer of a given JobType with an initial server count.
         *
         * Loads configuration from file and creates the specified number of servers.
         *
         * @param type The JobType handled by this load balancer.
         * @param numServers Initial number of servers in the pool.
         */
        LoadBalancer(JobType type, int numServers);

            /**
         * @brief Generates a request with a given probability.
         *
         * When a request is generated, its IPs are sampled from genRange and its time
         * is sampled uniformly from [minRequestTime, maxRequestTime]. If vFlag is true,
         * the request's source IP (inIP) is forced to be chosen from the provided valid list.
         *
         * @param prob Probability (0-100) that a request is generated.
         * @param vFlag If true, force the source IP to be chosen from @p valid.
         * @param valid A list of valid source IPs to sample from when vFlag is true.
         * @return A generated Request; may return a default/empty request if none generated.
         */
        Request generateRequest(int prob, bool vFlag, std::vector<std::string> valid);

        /**
         * @brief Loads configuration values from the config file into LBConfig.
         *
         * Parses threshold parameters, request generation parameters, firewall settings,
         * logging settings, and clock timing settings.
         *
         * @return true if the config file was opened and parsed successfully; false otherwise.
         */
        bool loadConfig();

        /**
         * @brief Sends the front request from this load balancer to another load balancer.
         *
         * Pops from this queue and pushes into the destination load balancer queue.
         *
         * @param lb Destination load balancer that will receive the request.
         * @return true if a request was sent; false if the queue was empty.
         */
        bool sendRequestLB(LoadBalancer& lb);

        /**
         * @brief Initializes another load balancer's queue with a prefilled workload.
         *
         * Pushes a fixed number of requests into the given load balancer's queue,
         * proportional to its server count. This is typically used to start the
         * simulation with an initial backlog.
         *
         * @param LB The load balancer whose queue will be initialized.
         */
        void initQueue(LoadBalancer& LB);

        /**
         * @brief Assigns a queued request to an idle server if available.
         *
         * Attempts to find the first idle server and assign the front request in the queue.
         *
         * @return true if a request was assigned; false if no servers were available or queue empty.
         */
        bool sendRequest();

        /**
         * @brief Receives a request by pushing it into this load balancer's queue.
         *
         * @param req Request to enqueue.
         * @return true if enqueue succeeded; false otherwise.
         */
        bool recieveRequest(Request& req);

        /**
         * @brief Advances the simulation by one tick for this load balancer and provided LBs.
         *
         * Increments time, decrements active requests on servers, marks completed requests,
         * and dispatches queued requests onto idle servers. Also applies an optional sleep
         * to simulate a clock period.
         *
         * @param LBs Vector of load balancer pointers to advance this tick.
         * @return The current time after ticking.
         */
        int tick(std::vector<LoadBalancer*> LBs);

        /**
         * @brief Sets the internal simulation clock for this load balancer.
         *
         * @param time New clock time in ticks.
         */
        void setClock(int time); 
        /**
         * @brief Returns the current simulation time for this load balancer.
         *
         * @return Current time in ticks.
         */
        int getTime();

        /**
         * @brief Adds a server to this load balancer's server pool.
         *
         * Increments the scale-up statistic and logs the event.
         *
         * @param ser The server instance to add.
         * @return Updated number of servers after insertion.
         */
        int addServer(const Server& ser); 

        /**
         * @brief Removes an idle server from the server pool, if one exists.
         *
         * Only idle servers may be removed. Increments scale-down statistic and logs the event.
         *
         * @return Updated number of servers after deletion attempt.
         */
        int deleteServer();

        /**
         * @brief Returns the current configuration of this load balancer.
         *
         * @return LBConfig containing simulation configuration values.
         */
        LBConfig getConfig(); 

        /**
         * @brief Returns statistics collected by this load balancer.
         *
         * @return LBStats containing counts of request outcomes and scaling.
         */
        LBStats getStats();


        /**
         * @brief Returns the current size of the request queue.
         *
         * @return Number of queued requests.
         */
        int queueSize();


        /**
         * @brief Returns the number of servers currently managed by this load balancer.
         *
         * @return Server count.
         */
        int serverCount();


        /**
         * @brief Returns the JobType serviced by this load balancer.
         *
         * @return The load balancer's JobType.
         */
        JobType getType();


        /**
         * @brief Logs a message to console with color-coding and appends it to the log file.
         *
         * Event messages are colored based on keywords (Accepted, Rejected, Added, Deleted, etc.).
         *
         * @param msg Message to log.
         */
        void logEvent(std::string msg); 


        /**
         * @brief Applies firewall filtering and rate-limiting rules to a request.
         *
         * Rejects requests from IPs not in the accepted range. Tracks the number of requests
         * from each IP inside a time window and temporarily bans an IP if it exceeds maxPing.
         *
         * @param req The request to evaluate.
         * @return true if accepted; false if rejected/blocked.
         */
        bool firewall(Request& req);


        /**
         * @brief Logs collected statistics to the log file and prints them to stdout.
         */
        void logStats();

        /**
         * @brief Logs starting and ending queue sizes for streaming and processing LBs.
         *
         * @param fqs Starting streaming queue size.
         * @param fqp Starting processing queue size.
         * @param lqs Ending streaming queue size.
         * @param lqp Ending processing queue size.
         */
        void logQueue(int fqs, int fqp, int lqs, int lqp);


        /**
         * @brief Aggregates statistics from a set of load balancers into this instance.
         *
         * Intended to merge scale and completion/acceptance statistics from other LBs.
         *
         * @param LBs Vector of load balancer pointers whose stats will be accumulated.
         */
        void syncStats(std::vector<LoadBalancer*> LBs);


    private:
        /** @brief JobType serviced by this load balancer. */
        JobType type; 
        /** @brief Current time (in ticks) for this load balancer. */
        int time; 
        /** @brief FIFO queue storing pending requests. */
        std::queue<Request> q;
        /** @brief Pool of servers that process queued requests. */
        std::vector<Server> servers; 
        /** @brief Configuration parameters loaded from file. */
        LBConfig config; 
        /** @brief Statistics counters for this load balancer. */
        LBStats stats;

        /**
         * @brief Map of blocked IP addresses to the tick time at which they were banned.
         *
         * Used to determine when a ban expires based on blockDuration.
         */
        std::map<std::string, int> banned; //ip : when first blocked
        /**
         * @brief Map tracking per-IP request counts within a time window.
         *
         * Maps: IP -> (count, windowStartTime)
         */
        std::map<std::string, std::pair<int, int> > seen; //ip : (count, first seen)
        /** @brief Output stream for event logging. */
        std::ofstream logFile; 
        /** @brief Input stream for configuration file parsing. */
        std::ifstream configFile; 
};