#pragma once

#include <string>


/**
 * @enum JobType
 * @brief Represents the category of work a request or server handles.
 *
 * JobType defines the classification of a request within the system.
 * These values are used to route requests to the appropriate
 * LoadBalancer and Server instances.
 *
 * The numeric assignments are explicitly defined to allow
 * deterministic integer conversions when scaling or routing.
 */
enum class JobType {
    Management = 2,
    Processing = 1,
    Streaming = 0


};

/**
 * @namespace JobUtil
 * @brief Utility functions for converting between JobType and other representations.
 *
 * This namespace provides helper functions to convert JobType values
 * to and from integers and strings. These conversions are commonly used
 * when indexing load balancers, logging events, or printing output.
 */
namespace JobUtil{
    /**
     * @brief Converts an integer to a JobType.
     *
     * @param i Integer representation of a JobType.
     * @return Corresponding JobType value.
     */
    JobType intToJob(int i);

    /**
     * @brief Converts a JobType to a human-readable string.
     *
     * @param type The JobType to convert.
     * @return String representation of the JobType.
     */
    std::string jobToString(JobType type);

    /**
     * @brief Converts a JobType to its integer representation.
     *
     * @param type The JobType to convert.
     * @return Integer corresponding to the JobType.
     */
    int jobToInt(JobType type);
}

/**
 * @struct Request
 * @brief Represents a single network request handled by the system.
 *
 * A Request contains:
 * - Source IP address (inIP)
 * - Destination IP address (outIP)
 * - Processing time (time)
 * - Associated JobType
 *
 * Requests are generated by the management load balancer and routed
 * to either Streaming or Processing load balancers depending on type.
 */
struct Request {

    std::string inIP;
    std::string outIP;
    int time;
    JobType type;
    /**
     * @brief Default constructor.
     *
     * Initializes a request with empty IP addresses,
     * zero processing time, and a default JobType of Management.
     */
    Request();
    /**
     * @brief Parameterized constructor.
     *
     * @param inIP Source IP address of the request.
     * @param outIP Destination IP address of the request.
     * @param time Processing time required for the request.
     * @param type The JobType classification of the request.
     */
    Request(std::string inIP, std::string outIP, int time, JobType type);
};